version: "2"
services:
  # name of the server you want to run is "main" or whatever
  main:
    container_name: im2-project-main
    image: mattrayner/lamp:latest
    volumes:
      - ".:/app"
      - "./mysql:/mysql"
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      # external_port:internal_port
      - "8080:80"
      - "3021:3306"
    tmpfs:
      - /var/lib/mysql
